<a href="https://colab.research.google.com/github/ThumulaRumesh/Smart-Homes---Indoor-Scene-Recognition-from-Images---CNN/blob/develop/01_Class_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import

In [ ]:
import os
import pandas as pd

Step 1 — Inspect the dataset

In [ ]:
# ==============================
# 2. Set dataset path
# ==============================

DATASET_PATH = "/content/drive/MyDrive/Colab Notebooks/Y 02 S 02, Advance ML/Assignment/MIT Indoor Scenes/indoorCVPR_09/Images"

print("Dataset exists:", os.path.exists(DATASET_PATH))
print("Dataset path:", DATASET_PATH)

Dataset exists: True
Dataset path: /content/drive/MyDrive/Colab Notebooks/Y 02 S 02, Advance ML/Assignment/MIT Indoor Scenes/indoorCVPR_09/Images

In [ ]:
# ==============================
# 3. Inspect folders
# ==============================

original_image_counts = {}

for class_folder in os.listdir(DATASET_PATH):
    class_path_full = os.path.join(DATASET_PATH, class_folder)

    if os.path.isdir(class_path_full):
        images_in_folder = [f for f in os.listdir(class_path_full) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
        original_image_counts[class_folder] = len(images_in_folder)


sorted_image_counts = sorted(original_image_counts.items(), key=lambda item: item[1], reverse=True)

print("Types of places sorted by image count (descending):")
for class_name, count in sorted_image_counts:
    print(f"- {class_name}: {count} images")

Types of places sorted by image count (descending):
- kitchen: 734 images
- livingroom: 706 images
- bedroom: 662 images
- airport_inside: 608 images
- bar: 604 images
- subway: 539 images
- casino: 515 images
- restaurant: 513 images
- warehouse: 506 images
- inside_subway: 457 images
- bakery: 405 images
- pantry: 384 images
- bookstore: 380 images
- toystore: 347 images
- corridor: 346 images
- laundromat: 276 images
- dining_room: 274 images
- winecellar: 269 images
- deli: 258 images
- locker_room: 249 images
- hairsalon: 239 images
- meeting_room: 233 images
- gym: 231 images
- bowling: 213 images
- grocerystore: 213 images
- bathroom: 197 images
- church_inside: 180 images
- auditorium: 176 images
- mall: 176 images
- movietheater: 175 images
- poolinside: 174 images
- museum: 168 images
- tv_studio: 166 images
- jewelleryshop: 157 images
- stairscase: 155 images
- trainstation: 153 images
- waitingroom: 151 images
- nursery: 144 images
- artstudio: 140 images
- closet: 135 images
- operating_room: 135 images
- dentaloffice: 131 images
- gameroom: 127 images
- kindergarden: 127 images
- laboratorywet: 125 images
- cloister: 120 images
- fastfood_restaurant: 116 images
- shoeshop: 116 images
- computerroom: 114 images
- classroom: 113 images
- children_room: 112 images
- buffet: 111 images
- videostore: 110 images
- office: 109 images
- studiomusic: 108 images
- library: 107 images
- restaurant_kitchen: 107 images
- clothingstore: 106 images
- concert_hall: 103 images
- florist: 103 images
- garage: 103 images
- prisoncell: 103 images
- inside_bus: 102 images
- elevator: 101 images
- greenhouse: 101 images
- hospitalroom: 101 images
- lobby: 101 images

In [ ]:
# ==============================
# 4. Count images in each class
# ==============================

class_counts = {}

for class_name in sorted(os.listdir(DATASET_PATH)):
    class_path = os.path.join(DATASET_PATH, class_name)

    if os.path.isdir(class_path):
        image_count = 0

        for file in os.listdir(class_path):
            if file.lower().endswith(('.jpg', '.jpeg', '.png')):
                image_count += 1

        class_counts[class_name] = image_count

class_df = pd.DataFrame(
    list(class_counts.items()),
    columns=["Class", "Image_Count"]
)

class_df = class_df.sort_values("Image_Count", ascending=False)

class_df

             Class  Image_Count
37         kitchen          734
41      livingroom          706
6          bedroom          662
0   airport_inside          608
4              bar          604
..             ...          ...
33      inside_bus          102
32    hospitalroom          101
28      greenhouse          101
23        elevator          101
42           lobby          101

[67 rows x 2 columns]

In [ ]:
# Classes with approximately 600 images

class_df[
    (class_df["Image_Count"] >= 500) &
    (class_df["Image_Count"] <= 750)
]

             Class  Image_Count
37         kitchen          734
41      livingroom          706
6          bedroom          662
0   airport_inside          608
4              bar          604
59          subway          539
10          casino          515
54      restaurant          513
65       warehouse          506